rosbag_convert_hz: 5
joint_states_topic: /joint_states
image_topic: /kinect_head/rgb/image_rect_color/compressed
control_joints: [
    {name: r_shoulder_pan_joint, type: revolute},
    {name: r_shoulder_lift_joint, type: revolute},
    {name: r_upper_arm_roll_joint, type: revolute},
    {name: r_elbow_flex_joint, type: revolute},
    {name: r_forearm_roll_joint, type: continuous, clamp: False},
    {name: r_wrist_flex_joint, type: revolute},
    {name: r_wrist_roll_joint, type: continuous, clamp: False}]
init_joint_names: [
    torso_lift_joint,
    r_shoulder_pan_joint,
    r_shoulder_lift_joint,
    r_upper_arm_roll_joint,
    r_elbow_flex_joint,
    r_forearm_roll_joint,
    r_wrist_flex_joint,
    r_wrist_roll_joint,
    l_shoulder_pan_joint,
    l_shoulder_lift_joint,
    l_upper_arm_roll_joint,
    l_elbow_flex_joint,
    l_forearm_roll_joint,
    l_wrist_flex_joint,
    l_wrist_roll_joint,
    head_tilt_joint,
]
init_joint_angles: [
    0.3,
    -1.3089969389957472,
    0.2726646259971648,
    -1.9198621771937625,
    -1.9198621771937625,
    0.3490658503988659,
    -0.17453292519943295,
    -0.17453292519943295,
    1.8089969389957472,
    0.2726646259971648,
    1.9198621771937625,
    -1.9198621771937625,
    -0.3490658503988659,
    -0.17453292519943295,
    -0.17453292519943295,
    1.2
]
image_config:
    x_min: 180
    x_max: 430
    y_min: 180
    y_max: 460
    resolution: 224
initial_joints:
- {type: prismatic, name: torso_lift_joint, value: 0.2998492114651644}
- {type: revolute, name: l_shoulder_pan_joint, value: 1.3085093464420279}
- {type: revolute, name: l_shoulder_lift_joint, value: 0.8726545105347081}
- {type: revolute, name: l_upper_arm_roll_joint, value: 1.9197462652738873}
- {type: revolute, name: l_elbow_flex_joint, value: -1.9199223812066033}
- {clamp: false, type: continuous, name: l_forearm_roll_joint, value: -0.349132373417342}
- {type: revolute, name: l_wrist_flex_joint, value: -0.17449684012804845}
- {clamp: false, type: continuous, name: l_wrist_roll_joint, value: -0.17457157142722046}
- {type: revolute, name: r_shoulder_pan_joint, value: -0.5903854801609619}
- {type: revolute, name: r_shoulder_lift_joint, value: 0.04815176362602333}
- {type: revolute, name: r_upper_arm_roll_joint, value: -1.0313749986855425}
- {type: revolute, name: r_elbow_flex_joint, value: -1.858684370291371}
- {clamp: false, type: continuous, name: r_forearm_roll_joint, value: 4.717978284546169}
- {type: revolute, name: r_wrist_flex_joint, value: -1.9993742211162415}
- {clamp: false, type: continuous, name: r_wrist_roll_joint, value: -3.5151812507972098}
- {type: revolute, name: head_pan_joint, value: -9.249018477613404e-05}
- {type: revolute, name: head_tilt_joint, value: 1.0730633307111537}
- {type: prismatic, name: l_gripper_joint, value: 0.08613262140600346}
- {type: prismatic, name: r_gripper_joint, value: 0.08695463222281463}
