rosbag_convert_hz: 5
joint_states_topic: /joint_states
image_topic: /kinect_head/rgb/image_rect_color/compressed
control_joints: [
    {name: r_shoulder_pan_joint, type: revolute},
    {name: r_shoulder_lift_joint, type: revolute},
    {name: r_upper_arm_roll_joint, type: revolute},
    {name: r_elbow_flex_joint, type: revolute},
    {name: r_forearm_roll_joint, type: continuous, clamp: True},
    {name: r_wrist_flex_joint, type: revolute},
    {name: r_wrist_roll_joint, type: continuous, clamp: True}]
init_joint_names: [
    torso_lift_joint,
    r_shoulder_pan_joint,
    r_shoulder_lift_joint,
    r_upper_arm_roll_joint,
    r_elbow_flex_joint,
    r_forearm_roll_joint,
    r_wrist_flex_joint,
    r_wrist_roll_joint,
    l_shoulder_pan_joint,
    l_shoulder_lift_joint,
    l_upper_arm_roll_joint,
    l_elbow_flex_joint,
    l_forearm_roll_joint,
    l_wrist_flex_joint,
    l_wrist_roll_joint,
    head_tilt_joint,
]
init_joint_angles: [
    0.3,
    -1.3089969389957472,
    0.2726646259971648,
    -1.9198621771937625,
    -1.9198621771937625,
    0.3490658503988659,
    -0.17453292519943295,
    -0.17453292519943295,
    1.8089969389957472,
    0.2726646259971648,
    1.9198621771937625,
    -1.9198621771937625,
    -0.3490658503988659,
    -0.17453292519943295,
    -0.17453292519943295,
    1.2
]
image_config:
    x_min: 150
    x_max: 400
    y_min: 180
    y_max: 460
    resolution: 224
initial_joints:
- {type: prismatic, name: torso_lift_joint, value: 0.2996728157795441}
- {type: revolute, name: l_shoulder_pan_joint, value: 1.30900678614617}
- {type: revolute, name: l_shoulder_lift_joint, value: 0.8726545105347083}
- {type: revolute, name: l_upper_arm_roll_joint, value: 1.919906620100257}
- {type: revolute, name: l_elbow_flex_joint, value: -1.919922381206603}
- {clamp: false, type: continuous, name: l_forearm_roll_joint, value: -0.3490166792434409}
- {type: revolute, name: l_wrist_flex_joint, value: -0.17456043008819355}
- {clamp: false, type: continuous, name: l_wrist_roll_joint, value: -0.17454814354716675}
- {type: revolute, name: r_shoulder_pan_joint, value: -0.4254842182379171}
- {type: revolute, name: r_shoulder_lift_joint, value: 0.8127206786440845}
- {type: revolute, name: r_upper_arm_roll_joint, value: -0.7709587606608473}
- {type: revolute, name: r_elbow_flex_joint, value: -2.0623767612079944}
- {clamp: false, type: continuous, name: r_forearm_roll_joint, value: 2.9372135598601146}
- {type: revolute, name: r_wrist_flex_joint, value: -1.185171718252486}
- {clamp: false, type: continuous, name: r_wrist_roll_joint, value: -4.215295715239812}
- {type: revolute, name: head_pan_joint, value: 1.2229570343530536e-05}
- {type: revolute, name: head_tilt_joint, value: 1.1124379586361457}
- {type: prismatic, name: l_gripper_joint, value: 0.08510372837233254}
- {type: prismatic, name: r_gripper_joint, value: 0.08758035067941015}